package io.vertx.messagerie_vertx.database;

import io.vertx.core.AbstractVerticle;
import io.vertx.core.Future;
import io.vertx.core.Promise;
import io.vertx.core.json.JsonObject;
import io.vertx.ext.jdbc.JDBCClient;

public class DatabaseVerticle extends AbstractVerticle {

    private JDBCClient dbClient;

    @Override
    public void start(Promise<Void> startPromise) {
        dbClient = JDBCClient.createShared(vertx, new JsonObject()
                .put("url", "jdbc:hsqldb:file:db/chat_db")
                .put("driver_class", "org.hsqldb.jdbcDriver")
                .put("max_pool_size", 30));

        initializeDatabase()
                .onSuccess(v -> {
                    MessagingService service = MessagingService.create(dbClient);
                    vertx.eventBus().consumer("database-service-address",
                            new MessagingServiceVertxProxyHandler(vertx, service));
                    startPromise.complete();
                })
                .onFailure(startPromise::fail);
    }

    private Future<Void> initializeDatabase() {
        Promise<Void> promise = Promise.promise();
        String sql = "CREATE TABLE IF NOT EXISTS messages (" +
                "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "user_name VARCHAR(255), " +
                "content VARCHAR(1000), " +
                "timestamp BIGINT)";

        dbClient.update(sql, res -> {
            if (res.succeeded()) {
                promise.complete();
            } else {
                promise.fail(res.cause());
            }
        });
        return promise.future();
    }
}
